### ISSUE TITLE
Unhandled Rejection (ReferenceError): Cannot access 'emscriptenModule' before initialization

### ISSUE THREAD

**Issue by Aloento** [jamsinclair/jSquash#13]
I'm using Webpack 5 with
```ts
    memo.set('experiments', {
      asyncWebAssembly: true,
      syncWebAssembly: true,
    });

    memo.module
      .rule('wasm')
      .test(/\.wasm/)
      .type('asset/resource');
```

**Comment by Aloento** [comment]
`Unhandled Rejection (TypeError): moduleFactory is not a function`

**Comment by jamsinclair** [comment]
I'm not familiar with the webpack tools you're using. We'll need more information to be able to help 🤓 
- Do you have a git repository or reproducible code sample that can I use to replicate?
- Which packages are you using and what versions are that?

There shouldn't be much configuration required. You can see a working Webpack 5 example at https://github.com/jamsinclair/jSquash/tree/main/examples/with-webpack
