### ISSUE TITLE
Possibility of converting an image to AVIF without losing quality

### ISSUE THREAD

**Issue by patratel** [jamsinclair/jSquash#29]
Hi,

I was wondering if there is any way of converting an image without losing quality. I've tried tweaking with the encode options to no avail(mostly the cqLevel). It's mostly visible when i convert low rez images, and less so when using high rez images. These are the current options I'm now using

`    cqLevel: 10,
    cqAlphaLevel: -1,
    denoiseLevel: 0,
    tileColsLog2: 0,
    tileRowsLog2: 0,
    speed: 6,
    subsample: 1,
    chromaDeltaQ: false,
    sharpness: 0,`

**Comment by jamsinclair** [comment]
Good question @patratel . Sounds like you want `lossless` encoding. Your settings look like they're almost there. 

Based on the Squoosh code – you'll need following values to trigger `lossless` mode

- `cqLevel: 0`
- `cqAlphaLevel: -1`
- `subsample: 3`

That should activate this branch of the code and hopefully give you lossless conversion 🤞 
https://github.com/jamsinclair/jSquash/blob/f662d8c9e1599129fd2108cbe22aff7a713958fb/packages/avif/codec/enc/avif_enc.cpp#L61-L63

**Comment by patratel** [comment]
Hey thank you for your answer. This did the trick!

**Comment by jamsinclair** [comment]
Great to hear! I'll mark this as resolved and close then 👍

**Comment by jamsinclair** [comment]
ℹ  Note: Users who stumble across this issue, I've added a simple boolean `lossless` encoding option that can be configured for `@jsquash/avif` packages greater than v2.1.0. Setting this option to `true` will configure the right properties to generate a lossless image.

See: https://github.com/jamsinclair/jSquash/pull/86
