### ISSUE TITLE
Add worker helper or example?

### ISSUE THREAD

**Issue by jamsinclair** [jamsinclair/jSquash#3]

**Comment by marklundin** [comment]
@jamsinclair Is there anything specific that needs to be done to run this in a worker?

**Comment by jamsinclair** [comment]
@marklundin, nope so long as you can import them and bundle the worker yourself it should be fine!

The only known issue is #37.

**Comment by jamsinclair** [comment]
I've added an example at https://github.com/jamsinclair/jSquash/blob/main/examples/web-workers to show case how you can run the code from a Web Worker.

At this time I don't want to abstract the WebWorker part and leave that to the user. For several reasons:
- Different bundlers have different opinions on how Workers get handled and bundled
- It may be better to do several tasks in a worker rather than just run one operation
