### ISSUE TITLE
gif support?

### ISSUE THREAD

**Issue by Zerebokep** [jamsinclair/jSquash#48]
Any plans to add support for gifs?

**Comment by jamsinclair** [comment]
This project is based off https://github.com/GoogleChromeLabs/squoosh and aims to support the same codecs.

I don't intend on supporting gifs as part of this project. There may already be other good WASM based gif libraries that you can use!

I have tried in the past, but sadly the modules don't work properly. I'm open to PR improvements
- https://github.com/jamsinclair/gifski-lite
- https://github.com/jamsinclair/gifski-wasm
