### ISSUE TITLE
Nuxt build error: UMD and IIFE output formats are not supported for code-splitting builds.

### ISSUE THREAD

**Issue by fayazara** [jamsinclair/jSquash#55]
**Describe the bug**
Using with nuxt 3 works in dev environment, but breaks during the production build

Error: `Nuxt Build Error: [commonjs--resolver] Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.`

**To Reproduce**
1. Create a new nuxt project and install any of the jsquash codecs
2. Handle the transpiling in nuxt config
```
build: {
    transpile: [
      "@jsquash/png",
      "@jsquash/avif",
      "@jsquash/jpeg",
      "@jsquash/jxl",
      "@jsquash/oxipng",
      "@jsquash/png",
      "@jsquash/webp",
    ],
  },
  vite: {
    optimizeDeps: {
      exclude: [
        "@jsquash/avif",
        "@jsquash/jpeg",
        "@jsquash/jxl",
        "@jsquash/oxipng",
        "@jsquash/png",
        "@jsquash/webp",
      ],
    },
  },
  ```
3. run `npm run build`

**Comment by fayazara** [comment]
Okay, I installed the single threaded versions of avif, jpegxl and oxipng and it seems to be working now

**Comment by fayazara** [comment]
Closing this

**Comment by jamsinclair** [comment]
Thanks for opening this issue @fayazara.

With the newer Vite versions (v5.2.2+) we shouldn't need the single threaded versions anymore.

Could you try add the following vite config to see if it fixes your build?
```js
worker: {
    format: "es"
}
```

If you can confirm it, I'll update our README with the new information 👍

**Comment by fayazara** [comment]
Works, thanks @jamsinclair
