### ISSUE TITLE
background execution?

### ISSUE THREAD

**Issue by turbobuilt** [jamsinclair/jSquash#58]
**Describe the bug**
My page freezes when this is going. Is there a way to make this run on a background thread? I'm using the vite version.

Edit: just switched to the regular, and it still freezes (the spinner stops spinning) while converting

**To Reproduce**
just use it as usual

**Comment by jamsinclair** [comment]
Hi @turbobuilt,

That is to be expected as the code will be running on the main thread and will overwhelm the event loop and halt all everything until it completes.

We can use [WebWorkers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) to offload that work.

I've created an example app showing how to use WebWorkers at https://github.com/jamsinclair/jSquash/tree/main/examples/web-workers. You can see how the work is split between the following two files and how messages are passed between the workers:
- [main.js](https://github.com/jamsinclair/jSquash/blob/main/examples/web-workers/main.js)
- [worker.js](https://github.com/jamsinclair/jSquash/blob/main/examples/web-workers/worker.js)

I hope that helps!

**Comment by turbobuilt** [comment]
Whoops, my bad!
