### ISSUE TITLE
Document `init` methods

### ISSUE THREAD

**Issue by jamsinclair** [jamsinclair/jSquash#7]
All the modules expose an init function that allows the WASM binaries to be initialized in a custom way. This is useful for environments like Cloudflare Workers where WASM binaries are injected as global vars.

We lack written documentation for this. We should add info for this to all module `README`s.

**Comment by Josh-McFarlin** [comment]
Hi, I'm looking into these packages and it looks great! However, is there a reason why the `avif` package seems to have a different format for the `init` function (that also isn't exported)? 

https://github.com/jamsinclair/jSquash/blob/main/packages/avif/encode.ts

Thanks!

**Comment by jamsinclair** [comment]
@Josh-McFarlin I just hadn't got around to tidying it up! I'll take a look at touching it up 👍 

The reason why it's a bit different is that the codec has both single threaded and multi threaded builds. That slightly complicates the init setup.
